In [2]:
import os, glob
import numpy as np
MAIN_FOLDER = "/home/rilab/Project/real2sim-data-collection/data/"

In [2]:
check = np.empty(shape=(0,3))

for filename in sorted(glob.glob(f'{MAIN_FOLDER}/*/*/*'), key=os.path.getmtime):
    directory = os.path.join(filename,"xy_yaw.npy")
    if os.path.isfile(directory):
        print(directory) 
        # temp = np.load(directory)
    # check = np.append(check, temp[-1].reshape((1,3)), axis=0)


/home/rilab/Project/real2sim-data-collection/data/20230120-21:59:12/Trial 0/0. 20230120-22:01:51/xy_yaw.npy
/home/rilab/Project/real2sim-data-collection/data/20230120-21:59:12/Trial 0/1. 20230120-22:02:11/xy_yaw.npy
/home/rilab/Project/real2sim-data-collection/data/20230120-21:59:12/Trial 0/2. 20230120-22:02:56/xy_yaw.npy
/home/rilab/Project/real2sim-data-collection/data/20230120-21:59:12/Trial 0/3. 20230120-22:03:27/xy_yaw.npy
/home/rilab/Project/real2sim-data-collection/data/20230120-21:59:12/Trial 0/4. 20230120-22:03:49/xy_yaw.npy
/home/rilab/Project/real2sim-data-collection/data/20230120-21:59:12/Trial 0/5. 20230120-22:04:07/xy_yaw.npy
/home/rilab/Project/real2sim-data-collection/data/20230120-21:59:12/Trial 0/6. 20230120-22:04:25/xy_yaw.npy
/home/rilab/Project/real2sim-data-collection/data/20230120-21:59:12/Trial 0/7. 20230120-22:04:46/xy_yaw.npy
/home/rilab/Project/real2sim-data-collection/data/20230120-21:59:12/Trial 0/8. 20230120-22:05:05/xy_yaw.npy
/home/rilab/Project/real2sim

In [6]:
for filename in sorted(glob.glob(f'{MAIN_FOLDER}/*/*'), key=os.path.getmtime):
    directory = os.path.join(filename,"sim_traj.npy")
    # if os.path.isfile(directory):
    #     print(directory)

temp = np.load(directory)
print(temp)

[[[ 4.59600313e-09 -8.07590939e-11  5.63012081e-09]
  [-1.54949696e-04 -9.41289982e-05 -2.61429604e-02]
  [-3.35658842e-04 -4.00383753e-04 -1.15149103e-01]
  ...
  [ 1.31231070e+00 -1.32657215e-01  1.12038827e+00]
  [ 1.31787610e+00 -1.33289874e-01  1.20807815e+00]
  [ 1.32345378e+00 -1.33864060e-01  1.69487369e+00]]

 [[ 4.59600313e-09 -8.07590939e-11  5.63012081e-09]
  [ 5.05160715e-05 -1.00266465e-04 -2.81704385e-02]
  [ 2.54626560e-04 -3.13013210e-04 -7.77460933e-02]
  ...
  [ 1.29940689e+00 -1.96473449e-01  6.40665388e+00]
  [ 1.30226183e+00 -1.95008472e-01  6.41312551e+00]
  [ 1.30571496e+00 -1.93815440e-01  6.46136570e+00]]

 [[ 4.59600313e-09 -8.07590939e-11  5.63012081e-09]
  [-5.98470397e-05 -1.07439460e-04  7.91979879e-02]
  [-4.89560989e-05 -3.83605191e-04  2.41662160e-01]
  ...
  [ 1.27487981e+00 -1.54400289e-01  1.71837101e+01]
  [ 1.27538788e+00 -1.54034287e-01  1.69258194e+01]
  [ 1.27638662e+00 -1.53494120e-01  1.70882835e+01]]

 ...

 [[ 4.59600313e-09 -8.07590939e-11